//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace F135856ToDo
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBAccess : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBAccess object using the connection string found in the 'DBAccess' section of the application configuration file.
        /// </summary>
        public DBAccess() : base("name=DBAccess", "DBAccess")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBAccess object.
        /// </summary>
        public DBAccess(string connectionString) : base(connectionString, "DBAccess")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBAccess object.
        /// </summary>
        public DBAccess(EntityConnection connection) : base(connection, "DBAccess")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TODO> TODOes
        {
            get
            {
                if ((_TODOes == null))
                {
                    _TODOes = base.CreateObjectSet<TODO>("TODOes");
                }
                return _TODOes;
            }
        }
        private ObjectSet<TODO> _TODOes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TODOes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTODOes(TODO tODO)
        {
            base.AddObject("TODOes", tODO);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="f135856TODOModel", Name="TODO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TODO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TODO object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        /// <param name="deadline">Initial value of the Deadline property.</param>
        /// <param name="finished">Initial value of the finished property.</param>
        public static TODO CreateTODO(global::System.DateTime id, global::System.String title, global::System.String content, global::System.DateTime deadline, global::System.Boolean finished)
        {
            TODO tODO = new TODO();
            tODO.id = id;
            tODO.Title = title;
            tODO.Content = content;
            tODO.Deadline = deadline;
            tODO.finished = finished;
            return tODO;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.DateTime _id;
        partial void OnidChanging(global::System.DateTime value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Deadline
        {
            get
            {
                return _Deadline;
            }
            set
            {
                OnDeadlineChanging(value);
                ReportPropertyChanging("Deadline");
                _Deadline = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deadline");
                OnDeadlineChanged();
            }
        }
        private global::System.DateTime _Deadline;
        partial void OnDeadlineChanging(global::System.DateTime value);
        partial void OnDeadlineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean finished
        {
            get
            {
                return _finished;
            }
            set
            {
                OnfinishedChanging(value);
                ReportPropertyChanging("finished");
                _finished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("finished");
                OnfinishedChanged();
            }
        }
        private global::System.Boolean _finished;
        partial void OnfinishedChanging(global::System.Boolean value);
        partial void OnfinishedChanged();

        #endregion
    
    }

    #endregion
    
}
